python: "/root/miniconda3/envs/ppiflow_af3/bin/python"

PPIFlowStep:
  model_weights: "ckpts/antibody.ckpt"
  config: "/teams/YingChiLab_1702378116/MaishaZhang/PPIFlow-main/tool/PPIFlow/configs/inference_nanobody.yaml"

AbMPNNStep_stage1:
  chain_list: "A"
  num_seq_per_target: 1
  sampling_temp: 0.1
  batch_size: 1
  omit_AAs: "C"

FlowpackerStep_stage1:
  config_path: "/teams/YingChiLab_1702378116/MaishaZhang/PPIFlow-main/tools/flowpacker/config/inference/base.yaml"
  use_gt_masks: true
